- name: Download Helm installer
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz

- name: Extract Helm
  ansible.builtin.unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Install Helm binary
  ansible.builtin.copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin/helm"
    mode: '0755'
    remote_src: yes

- name: Add Prometheus Helm repo
  ansible.builtin.command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
