- name: Create monitoring namespace
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: monitoring
    state: present

- name: Install kube-prometheus-stack
  ansible.builtin.command: >
    helm upgrade --install prometheus prometheus-community/kube-prometheus-stack
    --namespace monitoring
    --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false
    --set grafana.enabled=true
  register: helm_install
  changed_when: "'deployed' in helm_install.stdout"
  
- name: Create ServiceMonitor for Django
  community.kubernetes.k8s:
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: django-monitor
        namespace: monitoring
        labels:
          release: prometheus  # Must match Helm release name
      spec:
        endpoints:
          - port: web  # Matches Django service port name
            interval: 30s
        selector:
          matchLabels:
            app: django-backend  # Label of your Django service
            
- name: Check Django /metrics endpoint
  ansible.builtin.uri:
    url: "http://backend-service:8000/metrics"
    return_content: yes
  register: django_metrics
  failed_when: django_metrics.status != 200
