- name: Configure Minikube API access for Jenkins
  hosts: minikube
  tasks:
    - name: Ensure Minikube exposes API to Jenkins controller IP
      command: |
        minikube kubectl -- proxy --address=0.0.0.0 --port=8001 --accept-hosts='.*' &
      async: 30  # Allow 30s for the command to start
      poll: 0  # Don’t check status afterward
      register: proxy_process
#kubectl port-forward --address 0.0.0.0 svc/backend-service 8000:8000
